# Generated by Django 3.0.4 on 2020-04-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newUser',
        ),
    ]
